import useBindStore from "@store/zustand";
import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { fakeProject1, fakeProject3, fakeUser1, fakeUser2 } from "@utils/testDummy";
import axios from "axios";
import ProjectManage from "./ProjectManage";
import ReactRouter from 'react-router';

const mockNavigate = jest.fn();
jest.mock('react-router', () => ({ ...jest.requireActual('react-router'), useNavigate: () => mockNavigate }));
jest.spyOn(global.window, 'alert').mockImplementation(() => {});

describe('<ProjectManage />', () => {
  let AD: JSX.Element;
  beforeAll(() => {
    AD = <ProjectManage />;
    global.matchMedia = global.matchMedia ?? function () {
      return {
        addListener: jest.fn(),
        removeListener: jest.fn()
      };
    };
  });
  it('should render without error/handle dissolve', async () => {
    axios.delete = jest.fn();
    const i = useBindStore.getState();
    i.selectedProject = fakeProject3;
    i.user = fakeUser1;
    useBindStore.setState(i, true);
    jest.spyOn(ReactRouter, 'useParams').mockReturnValue({ projectId: '1' });
    const { container } = render(AD);
    await waitFor(() => { expect(container.getElementsByClassName('invite-email')[0]).not.toBeTruthy(); });;
    const dissolveButton = screen.getAllByRole('button')[2];
    fireEvent.click(dissolveButton);
    await waitFor(() => { expect(container.getElementsByClassName('dissolve-desc')[0]).toBeInTheDocument(); });
    const buttons = screen.getAllByRole('button');
    const di = screen.getAllByRole('textbox')[2];
    fireEvent.change(di, { target: { value: 'a' } });
    await waitFor(() => { expect(buttons[5]).toBeEnabled() });
    fireEvent.click(buttons[5]);
    await waitFor(() => { expect(mockNavigate).toBeCalled(); });
  });
  it('should handle add new member', async () => {
    const i = useBindStore.getState();
    i.selectedProject = fakeProject3;
    useBindStore.setState(i, true);
    jest.spyOn(ReactRouter, 'useParams').mockReturnValue({ projectId: '1' });
    const { container } = render(AD);
    await waitFor(() => { expect(container.getElementsByClassName('invite-email')[0]).not.toBeTruthy(); });
    axios.get = jest.fn().mockResolvedValueOnce({ data: [fakeUser1, fakeUser2] }).mockResolvedValueOnce({ data: [fakeUser2] }).mockResolvedValueOnce({ data: fakeProject3 });
    const addButton = screen.getByText('Add a new member');
    fireEvent.click(addButton);
    const emailInput = screen.getByRole('combobox');
    fireEvent.change(emailInput, { target: { value: 'asdf' } });
    await waitFor(() => { expect(axios.get).toBeCalled(); });
    await waitFor(() => { expect(screen.getAllByText('fakeUser2@fake.com')[1]).toBeTruthy(); });
    const optionButton = screen.getAllByText('fakeUser2@fake.com')[1];
    await act( async () => { fireEvent.click(optionButton); });
    const buttons = screen.getAllByRole('button');
    const inviteButton = buttons[4];
    fireEvent.click(inviteButton);
    axios.put = jest.fn();
    const confirmButton = buttons[6];
    axios.delete = jest.fn();
    await act( async () => { fireEvent.click(confirmButton); });
  });
  it('should handle member delete', async () => {
    axios.delete = jest.fn();
    axios.get = jest.fn().mockResolvedValueOnce({ data: { fakeProject1 } });
    jest.spyOn(ReactRouter, 'useParams').mockReturnValue({ projectId: '1' });
    jest.spyOn(global.window, 'confirm').mockReturnValue(true);
    const i = useBindStore.getState();
    i.selectedProject = fakeProject1;
    i.user = fakeUser1;
    useBindStore.setState(i, true);
    await act(async () => { render(AD); });
    const deletes = screen.getAllByText('delete');
    await act(async () => { fireEvent.click(deletes[0]); });
  });
  it('should handle cancel member delete', async () => {
    axios.delete = jest.fn();
    axios.get = jest.fn().mockResolvedValueOnce({ data: { fakeProject1 } });
    jest.spyOn(ReactRouter, 'useParams').mockReturnValue({ projectId: '1' });
    jest.spyOn(global.window, 'confirm').mockReturnValue(false);
    const i = useBindStore.getState();
    i.selectedProject = fakeProject1;
    i.user = fakeUser1;
    useBindStore.setState(i, true);
    await act(async () => { render(AD); });
    const deletes = screen.getAllByText('delete');
    await act(async () => { fireEvent.click(deletes[0]); });
  });
  it('should handle cancel in add new memeber', async () => {
    jest.spyOn(ReactRouter, 'useParams').mockReturnValue({ projectId: '1' });
    const i = useBindStore.getState();
    i.selectedProject = fakeProject1;
    useBindStore.setState(i, true);
    await act(async () => { render(AD); });
    const addButton = screen.getByText('Add a new member');
    fireEvent.click(addButton);
    const buttons = screen.getAllByRole('button');
    fireEvent.click(buttons[5]);
  });
  it('should handle cancel in dissolve', async () => {
    jest.spyOn(ReactRouter, 'useParams').mockReturnValue({ projectId: '1' });
    const i = useBindStore.getState();
    i.selectedProject = fakeProject1;
    useBindStore.setState(i, true);
    await act(async () => { render(AD); });
    const dissolveButton = screen.getAllByRole('button')[2];
    fireEvent.click(dissolveButton);
    const buttons = screen.getAllByRole('button');
    fireEvent.click(buttons[4]);
  });
  it('should handle undefined projectId with add', async () => {
    jest.spyOn(ReactRouter, 'useParams').mockReturnValue({ projectId: undefined });
    const i = useBindStore.getState();
    i.selectedProject = fakeProject3;
    useBindStore.setState(i, true);
    const { container } = render(AD);
    await waitFor(() => { expect(container.getElementsByClassName('invite-email')[0]).not.toBeTruthy(); });
    axios.get = jest.fn().mockResolvedValueOnce({ data: [fakeUser1, fakeUser2] }).mockResolvedValueOnce({ data: [fakeUser2] }).mockResolvedValueOnce({ data: fakeProject3 });
    const addButton = screen.getByText('Add a new member');
    fireEvent.click(addButton);
    const emailInput = screen.getByRole('combobox');
    fireEvent.change(emailInput, { target: { value: 'asdf' } });
    await waitFor(() => { expect(axios.get).toBeCalled(); });
    await waitFor(() => { expect(screen.getAllByText('fakeUser2@fake.com')[1]).toBeTruthy(); });
    const optionButton = screen.getAllByText('fakeUser2@fake.com')[1];
    await act( async () => { fireEvent.click(optionButton); });
    const buttons = screen.getAllByRole('button');
    const inviteButton = buttons[4];
    fireEvent.click(inviteButton);
    axios.put = jest.fn();
    const confirmButton = buttons[6];
    axios.delete = jest.fn();
    await act( async () => { fireEvent.click(confirmButton); });
  });
  it('should handle undefined projectId in dissolve', async () => {
    axios.delete = jest.fn();
    const i = useBindStore.getState();
    i.selectedProject = fakeProject3;
    i.user = fakeUser1;
    useBindStore.setState(i, true);
    jest.spyOn(ReactRouter, 'useParams').mockReturnValue({ projectId: undefined });
    await act(async () => { render(AD); });
    const dissolveButton = screen.getAllByRole('button')[2];
    await act(async () => { fireEvent.click(dissolveButton); });
    const buttons = screen.getAllByRole('button');
    const di = screen.getAllByRole('textbox')[2];
    await act(async () => { fireEvent.change(di, { target: { value: 'a' } }); });
    await waitFor(() => { expect(buttons[5]).toBeEnabled() });
    await act(async () => { fireEvent.click(buttons[5]); });
  });
  it('should handle undefined projectId in delete', async () => {
    axios.delete = jest.fn();
    axios.get = jest.fn().mockResolvedValueOnce({ data: { fakeProject1 } });
    jest.spyOn(ReactRouter, 'useParams').mockReturnValue({ projectId: undefined });
    jest.spyOn(global.window, 'confirm').mockReturnValue(true);
    const i = useBindStore.getState();
    i.selectedProject = fakeProject1;
    i.user = fakeUser1;
    useBindStore.setState(i, true);
    await act(async () => { render(AD); });
    const deletes = screen.getAllByText('delete');
    await act(async () => { fireEvent.click(deletes[0]); });
  });
  it('should handle no delete when not manager', async () => {
    const i = useBindStore.getState();
    i.selectedProject = fakeProject1;
    i.user = fakeUser2;
    jest.spyOn(ReactRouter, 'useParams').mockReturnValue({ projectId: '1' });
    await act(async () => { render(AD); });
  });
  it('should handle change project name and subject', async () => {
    jest.spyOn(ReactRouter, 'useParams').mockReturnValue({ projectId: '1' });
    jest.spyOn(global.window, 'confirm').mockReturnValue(true);
    axios.put = jest.fn();
    axios.get = jest.fn().mockResolvedValue({ data: fakeProject1 });
    const i = useBindStore.getState();
    i.selectedProject = fakeProject1;
    i.user = fakeUser1;
    useBindStore.setState(i, true);
    await act(async () => { render(AD); });
    const texts = screen.getAllByRole('textbox');
    await act(async () => { fireEvent.change(texts[0], { target: { value: 'asdf' } }); });
    await act(async () => { fireEvent.change(texts[1], { target: { value: 'asdf' } }); });
    const buttons = screen.getAllByRole('button');
    await act(async () => { fireEvent.click(buttons[0]); });
  });
  it('should handle cancel change project name and subject', async () => {
    jest.spyOn(ReactRouter, 'useParams').mockReturnValue({ projectId: '1' });
    jest.spyOn(global.window, 'confirm').mockReturnValue(false);
    axios.put = jest.fn();
    axios.get = jest.fn().mockResolvedValue({ data: fakeProject1 });
    const i = useBindStore.getState();
    i.selectedProject = fakeProject1;
    i.user = fakeUser1;
    useBindStore.setState(i, true);
    await act(async () => { render(AD); });
    const texts = screen.getAllByRole('textbox');
    await act(async () => { fireEvent.change(texts[0], { target: { value: 'asdf' } }); });
    await act(async () => { fireEvent.change(texts[1], { target: { value: 'asdf' } }); });
    const buttons = screen.getAllByRole('button');
    await act(async () => { fireEvent.click(buttons[0]); });
  });
  it('should handle change project name and subject when projectId undefined', async () => {
    jest.spyOn(ReactRouter, 'useParams').mockReturnValue({ projectId: undefined });
    axios.put = jest.fn();
    axios.get = jest.fn().mockResolvedValue({ data: fakeProject1 });
    const i = useBindStore.getState();
    i.selectedProject = null;
    i.user = fakeUser1;
    useBindStore.setState(i, true);
    await act(async () => { render(AD); });
    const texts = screen.getAllByRole('textbox');
    await act(async () => { fireEvent.change(texts[0], { target: { value: 'asdf' } }); });
    await act(async () => { fireEvent.change(texts[1], { target: { value: 'asdf' } }); });
    const buttons = screen.getAllByRole('button');
    await act(async () => { fireEvent.click(buttons[0]); });
  });
  it('should handle leave click', async () => {
    jest.spyOn(ReactRouter, 'useParams').mockReturnValue({ projectId: '1' });
    jest.spyOn(global.window, 'confirm').mockReturnValue(true);
    axios.delete = jest.fn();
    axios.get = jest.fn().mockResolvedValue({ data: fakeProject1 });
    const i = useBindStore.getState();
    i.selectedProject = fakeProject1;
    i.user = fakeUser1;
    useBindStore.setState(i, true);
    await act(async () => { render(AD); });
    const leave = screen.getByText('leave');
    await act(async () => { fireEvent.click(leave); });
  });
  it('should handle cancel leave click', async () => {
    jest.spyOn(ReactRouter, 'useParams').mockReturnValue({ projectId: '1' });
    jest.spyOn(global.window, 'confirm').mockReturnValue(false);
    axios.delete = jest.fn();
    axios.get = jest.fn().mockResolvedValue({ data: fakeProject1 });
    const i = useBindStore.getState();
    i.selectedProject = fakeProject1;
    i.user = fakeUser1;
    useBindStore.setState(i, true);
    await act(async () => { render(AD); });
    const leave = screen.getByText('leave');
    await act(async () => { fireEvent.click(leave); });
  });
  it('should handle leave click when projectId undefined', async () => {
    jest.spyOn(ReactRouter, 'useParams').mockReturnValue({ projectId: undefined });
    jest.spyOn(global.window, 'confirm').mockReturnValue(true);
    axios.delete = jest.fn();
    axios.get = jest.fn().mockResolvedValue({ data: fakeProject1 });
    const i = useBindStore.getState();
    i.selectedProject = fakeProject1;
    i.user = fakeUser1;
    useBindStore.setState(i, true);
    await act(async () => { render(AD); });
    const leave = screen.getByText('leave');
    await act(async () => { fireEvent.click(leave); });
  });
});