# CI Environment
dist: bionic

# Job Configurations
jobs:
  include:
    - language: python
      python: "3.9.6"
      install:
        - cd backend
        - pip install -r requirements.txt
      script:
        - cd sprint
        - pylint **/*.py --load-plugins pylint-django
        - coverage run --source='.' manage.py test
        - coverage xml

    - language: node_js
      node_js: 14
      install:
        - cd frontend
        - cd sprint
        - yarn install
      script:
        - ./node_modules/.bin/eslint src
        - yarn test --coverage --watchAll=false