# Generated by Django 4.1.2 on 2022-12-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_user', '0003_userverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
