# Generated by Django 4.1.2 on 2022-12-03 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_project', '0003_alter_task_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='model_project.documentspace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentspace',
            name='head',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.CharField(max_length=100),
        ),
    ]
