# Generated by Django 4.1.2 on 2022-12-03 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_project', '0003_alter_task_assignee'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.IntegerField()),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model_project.comment')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model_project.document')),
                ('document_space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model_project.documentspace')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_project.task')),
                ('user_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_project.userproject')),
            ],
        ),
    ]
