# Generated by Django 4.1.2 on 2022-12-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_project', '0004_remove_document_head_document_space_and_more'),
        ('model_project', '0004_userprojectactivity'),
    ]

    operations = [
    ]
