# Generated by Django 4.1.2 on 2022-12-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_project', '0005_merge_20221204_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='on-going', max_length=100),
            preserve_default=False,
        ),
    ]
