# Generated by Django 4.1.2 on 2022-12-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_project', '0006_remove_document_head_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='on-going', max_length=100),
        ),
    ]
