# Generated by Django 4.1.2 on 2022-12-05 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('model_project', '0007_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprojectactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
