# Generated by Django 4.1.2 on 2022-12-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_project', '0008_alter_document_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document',
        ),
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
    ]
