# Generated by Django 4.1.2 on 2022-12-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_project', '0008_userprojectactivity_created_at'),
        ('model_project', '0009_remove_document_document_remove_document_name'),
    ]

    operations = [
    ]
