# Generated by Django 4.1.2 on 2022-12-10 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_project', '0010_merge_20221205_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprojectactivity',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model_project.task'),
        ),
    ]
